-- =========================================================
-- Hostel Hub - Seed Data
-- =========================================================
USE hostel_management;

-- ⚠️  IMPORTANT: Generate the password hash FIRST by running:
--     cd backend && node generate-hash.js
-- Then paste the output hash below before running this file.
--
-- Default credentials: admin / Admin@123  |  warden / Admin@123
-- The hash below is a PLACEHOLDER — replace it with the generated one.
--
-- Placeholder hash (for 'Admin@123' — generated by generate-hash.js):
SET @pwd_hash = '$2a$10$ItkpiLfw6U2yCrNWY4vLneNRkFUIAVLDHFzwkoIb0MWMz7sQYmIhS';

INSERT INTO users (username, password_hash, role, full_name, email, phone) VALUES
('admin',  @pwd_hash, 'admin',  'System Administrator', 'admin@hostel.edu',  '9999999999'),
('warden', @pwd_hash, 'warden', 'Mr. Rajesh Kumar',     'warden@hostel.edu', '9888888888');

-- Sample Rooms
INSERT INTO rooms (room_number, block, floor, capacity, room_type, is_ac, gender, monthly_rent, maintenance_status) VALUES
('101', 'A', 1, 2, 'Double', TRUE, 'Male', 8500.00, 'Good'),
('102', 'A', 1, 2, 'Double', TRUE, 'Male', 8500.00, 'Good'),
('103', 'A', 1, 3, 'Triple', FALSE, 'Male', 6000.00, 'Good'),
('201', 'A', 2, 1, 'Single', TRUE, 'Male', 12000.00, 'Good'),
('202', 'A', 2, 2, 'Double', TRUE, 'Male', 8500.00, 'Needs Maintenance'),
('101', 'B', 1, 2, 'Double', TRUE, 'Female', 8500.00, 'Good'),
('102', 'B', 1, 2, 'Double', FALSE, 'Female', 6500.00, 'Good'),
('103', 'B', 1, 3, 'Triple', FALSE, 'Female', 6000.00, 'Good'),
('201', 'B', 2, 1, 'Single', TRUE, 'Female', 12000.00, 'Good'),
('101', 'C', 1, 4, 'Dormitory', FALSE, 'Male', 4500.00, 'Good'),
('102', 'C', 1, 4, 'Dormitory', FALSE, 'Male', 4500.00, 'Under Maintenance'),
('201', 'C', 2, 4, 'Dormitory', FALSE, 'Female', 4500.00, 'Good');

-- Sample Students
INSERT INTO students (student_id, name, age, gender, date_of_birth, blood_group, phone, email, course, department, year, room_id, parent_name, parent_phone, emergency_contact_name, emergency_contact_phone, admission_date, status) VALUES
('HMS001', 'Arjun Sharma', 20, 'Male', '2004-03-15', 'O+', '9876543210', 'arjun@student.edu', 'B.Tech', 'Computer Science', 2, 1, 'Rajesh Sharma', '9876543200', 'Rajesh Sharma', '9876543200', '2023-07-01', 'Active'),
('HMS002', 'Priya Patel', 21, 'Female', '2003-06-22', 'A+', '9876543211', 'priya@student.edu', 'B.Tech', 'Electronics', 3, 6, 'Mohan Patel', '9876543201', 'Mohan Patel', '9876543201', '2022-07-01', 'Active'),
('HMS003', 'Rohit Singh', 19, 'Male', '2005-11-08', 'B+', '9876543212', 'rohit@student.edu', 'BCA', 'Computer Applications', 1, 2, 'Suresh Singh', '9876543202', 'Suresh Singh', '9876543202', '2024-07-01', 'Active'),
('HMS004', 'Sneha Gupta', 22, 'Female', '2002-09-14', 'AB+', '9876543213', 'sneha@student.edu', 'MCA', 'Computer Applications', 1, 7, 'Anil Gupta', '9876543203', 'Anil Gupta', '9876543203', '2024-07-01', 'Active'),
('HMS005', 'Vikram Kumar', 20, 'Male', '2004-01-25', 'O-', '9876543214', 'vikram@student.edu', 'B.Tech', 'Mechanical', 2, 3, 'Ravi Kumar', '9876543204', 'Ravi Kumar', '9876543204', '2023-07-01', 'Active'),
('HMS006', 'Ananya Reddy', 21, 'Female', '2003-04-30', 'A-', '9876543215', 'ananya@student.edu', 'B.Sc', 'Physics', 3, 6, 'Krishna Reddy', '9876543205', 'Krishna Reddy', '9876543205', '2022-07-01', 'Active'),
('HMS007', 'Karthik Nair', 20, 'Male', '2004-07-17', 'B-', '9876543216', 'karthik@student.edu', 'B.Tech', 'Civil', 2, 1, 'Gopalan Nair', '9876543206', 'Gopalan Nair', '9876543206', '2023-07-01', 'Active'),
('HMS008', 'Deepika Joshi', 19, 'Female', '2005-12-03', 'O+', '9876543217', 'deepika@student.edu', 'B.Com', 'Commerce', 1, 8, 'Ramesh Joshi', '9876543207', 'Ramesh Joshi', '9876543207', '2024-07-01', 'Active');

-- Update room occupancy
UPDATE rooms SET current_occupancy = 2 WHERE id = 1;  -- A-101: Arjun, Karthik
UPDATE rooms SET current_occupancy = 1 WHERE id = 2;  -- A-102: Rohit
UPDATE rooms SET current_occupancy = 1 WHERE id = 3;  -- A-103: Vikram
UPDATE rooms SET current_occupancy = 2 WHERE id = 6;  -- B-101: Priya, Ananya
UPDATE rooms SET current_occupancy = 1 WHERE id = 7;  -- B-102: Sneha
UPDATE rooms SET current_occupancy = 1 WHERE id = 8;  -- B-103: Deepika

-- Sample Fees
INSERT INTO fees (student_id, amount, due_date, paid_date, status, fee_type, month_year, payment_mode) VALUES
(1, 8500.00, '2024-07-10', '2024-07-08', 'Paid', 'Hostel Fee', '07-2024', 'Online'),
(2, 8500.00, '2024-07-10', '2024-07-09', 'Paid', 'Hostel Fee', '07-2024', 'Cash'),
(3, 8500.00, '2024-07-10', NULL, 'Overdue', 'Hostel Fee', '07-2024', NULL),
(4, 6500.00, '2024-07-10', '2024-07-05', 'Paid', 'Hostel Fee', '07-2024', 'Online'),
(5, 6000.00, '2024-07-10', NULL, 'Pending', 'Hostel Fee', '07-2024', NULL),
(6, 8500.00, '2024-07-10', '2024-07-10', 'Paid', 'Hostel Fee', '07-2024', 'Cheque'),
(7, 8500.00, '2024-07-10', NULL, 'Overdue', 'Hostel Fee', '07-2024', NULL),
(8, 6000.00, '2024-07-10', '2024-07-07', 'Paid', 'Hostel Fee', '07-2024', 'Online'),
(1, 8500.00, '2024-08-10', NULL, 'Pending', 'Hostel Fee', '08-2024', NULL),
(2, 8500.00, '2024-08-10', NULL, 'Pending', 'Hostel Fee', '08-2024', NULL);

-- Sample Complaints
INSERT INTO complaints (student_id, category, description, priority, status, assigned_to) VALUES
(1, 'WiFi', 'WiFi connection dropping frequently in room A-101 during evenings.', 'High', 'In Progress', 'IT Department'),
(3, 'Plumbing', 'Water leakage from bathroom tap in A-102. Needs immediate fixing.', 'High', 'Pending', NULL),
(5, 'Electricity', 'Power socket not working near study table in A-103.', 'Medium', 'Resolved', 'Maintenance Team'),
(2, 'Cleaning', 'Common bathroom on Block B floor 1 not cleaned properly.', 'Low', 'Pending', NULL),
(7, 'Furniture', 'Study chair is broken in room A-101. Needs replacement.', 'Medium', 'Pending', NULL);

-- Sample Visitors
INSERT INTO visitors (student_id, visitor_name, relation, phone, id_proof_type, id_proof_number, purpose, check_in, check_out) VALUES
(1, 'Rajesh Sharma', 'Father', '9876543200', 'Aadhaar', '123456789012', 'Monthly visit', '2024-07-05 10:00:00', '2024-07-05 17:00:00'),
(2, 'Sunita Patel', 'Mother', '9876543201', 'Voter ID', 'ABC1234567', 'Dropped luggage', '2024-07-08 11:00:00', '2024-07-08 13:00:00'),
(3, 'Amit Singh', 'Brother', '9876543290', 'Driving License', 'DL-1234567', 'Casual visit', '2024-07-09 14:00:00', NULL);

-- Sample Leave Requests
INSERT INTO leave_requests (student_id, from_date, to_date, reason, leave_type, status, reviewed_by) VALUES
(1, '2024-07-15', '2024-07-20', 'Going home for Eid festival celebrations with family.', 'Home Visit', 'Approved', 'Mr. Rajesh Kumar'),
(3, '2024-07-12', '2024-07-14', 'Medical appointment in home city.', 'Medical', 'Pending', NULL),
(5, '2024-07-18', '2024-07-22', 'Sister wedding ceremony.', 'Personal', 'Approved', 'Mr. Rajesh Kumar'),
(2, '2024-07-25', '2024-07-28', 'Personal family matter.', 'Personal', 'Rejected', 'Mr. Rajesh Kumar');

-- Sample Notices
INSERT INTO notices (title, content, category, target_audience, posted_by, is_active, expires_at) VALUES
('Fee Payment Reminder - July 2024', 'All students are reminded that hostel fee for July 2024 is due on 10th July. Late payment will attract a fine of Rs. 50 per day.', 'Fee', 'Students', 'admin', TRUE, '2024-07-15'),
('Water Supply Maintenance', 'Water supply will be temporarily suspended on 12th July 2024 from 9 AM to 1 PM for maintenance work. Please store water accordingly.', 'Maintenance', 'All', 'admin', TRUE, '2024-07-12'),
('Independence Day Celebration', 'Students are invited to participate in the Independence Day celebration on 15th August 2024 at the hostel ground. Attendance is mandatory.', 'Event', 'All', 'admin', TRUE, '2024-08-15'),
('New WiFi Password', 'The WiFi password has been updated. New password will be shared by the warden personally. Do not share with outsiders.', 'General', 'Students', 'warden', TRUE, NULL),
('Mess Menu Update', 'The mess menu has been updated for the month of July. Vegetarian options have been added on Mondays and Thursdays.', 'General', 'Students', 'admin', TRUE, NULL);

-- Sample Attendance (last 7 days)
INSERT INTO attendance (student_id, date, check_in_time, check_out_time, status, marked_by) VALUES
(1, '2024-07-08', '09:00:00', '22:00:00', 'Present', 'warden'),
(2, '2024-07-08', '08:30:00', '21:30:00', 'Present', 'warden'),
(3, '2024-07-08', NULL, NULL, 'Absent', 'warden'),
(4, '2024-07-08', '10:00:00', '20:00:00', 'Present', 'warden'),
(5, '2024-07-08', NULL, NULL, 'On Leave', 'warden'),
(6, '2024-07-08', '09:30:00', '22:30:00', 'Present', 'warden'),
(7, '2024-07-08', '08:00:00', '23:00:00', 'Present', 'warden'),
(8, '2024-07-08', '09:00:00', '21:00:00', 'Present', 'warden');

-- Sample Notifications
INSERT INTO notifications (user_id, title, message, type, is_read) VALUES
(1, 'New Complaint Submitted', 'Student HMS003 has submitted a new plumbing complaint.', 'Complaint', FALSE),
(1, 'Fee Overdue Alert', '2 students have overdue fee payments for July 2024.', 'Fee', FALSE),
(1, 'Leave Request Pending', 'HMS003 has submitted a leave request for 12-14 July.', 'Leave', TRUE),
(2, 'New Notice Posted', 'A new notice has been posted: Fee Payment Reminder.', 'Notice', FALSE);
